### ISSUE TITLE
Efficiency vs KevinBoone's epub2txt

### ISSUE THREAD

**Issue by teamcoltra** [quininer/epub2txt#2]
I will run my own tests soon but I was wondering if you have already run any tests comparing your tool to the existing KevinBoone tool and what are the differences in output and speed and whatever between the two?

Thanks :)

**Comment by quininer** [comment]
Ha, I did not carry out any formal tests. I created this tool just because I need to read epub formatted novels.

I doubt it will not have any advantage on performance.

**Comment by teamcoltra** [comment]
I will still check the two out. Our use case is very similar but at the volume I convert books efficiency becomes a priority. I will compare the two and let you know what I find, efficiency isn't everything I also will see how you both handle content as well. In a few days I should have a nice little side-by-side

**Comment by teamcoltra** [comment]
Here are my results, I think it's clear that you are the winner. When I add ASCII conversation to his it ads .01 second to conversion and the output still isn't as good as yours. It would be nice to see ASCII conversion from your script but so far it looks great. One thing is the table of contents with yours includes some of the epub file.

```
Kevin Execution time: 0.965320 seconds
quininer Execution time: 0.070131 seconds
quininer Execution time: 0.072631 seconds
Kevin Execution time: 0.981680 seconds
quininer Execution time: 0.070950 seconds
Kevin Execution time: 0.941851 seconds
```


> 
> Title Page
> 
> Copyright
> 
> 1
> 
> 2
> 
> 3
> 
> 4
> 
> 5
> 
> 6
> 
> 7
> 
> 8
> 
> 9
> 
> 10
> 
> 11
> 
> 12
> 
> 13
> 
> 14
> 
> 15
> 
> 16
> 
> 17
> 
> 18
> 
> 19
> 
> 20
> 
> 21
> 
> 22
> 
> 23
> 
> 24
> 
> 25
> 
> 26
> 
> Becoming Us
> 
> By Allie Everhart
> 
> Becoming Us
> 
> By Allie Everhart
> 
> Copyright © 2014 Allie Everhart
> 
> All rights reserved.
> 
> Published by Waltham Publishing, LLC
> 
> Cover Design by Sarah Hansen of Okay Creations
> 
> Photo by Toski Covey Photography
> 
> This book is a work of fiction. The characters, things, and events are fictitious, and any similarities to real persons (live or dead), things, or events are coincidental and not intended by the author. Brand names of products mentioned in this book are used for reference only and the author acknowledges that any trademarks and product names are the property of their respective owners.
> 
> The author holds exclusive rights to this work and unauthorized duplication is prohibited. No part of this book is to be reproduced in any form without written permission from the author.
> 
> 1
> 
> JADE
> 
> The man stands in front of me as I sit in the chair. Weâ€™re in a small room in an abandoned building on the Camsburg campus. The man is tall, maybe 6â€™2, with dark hair that has flecks of gray in it. He looks handsome and sophisticated, wearing a black tailored suit. He has an average build, maybe a little on the thin side. His eyes are greenish-brown, his skin has a slight tan, and his face is just like his fatherâ€™s. I hadnâ€™t realized how similar they look. Iâ€™ve only seen a couple photos, but seeing him up close, he looks just like his dad, even more so than his brother did.
> 
> I meet his gaze, trying to remain calm even though my heart is pounding in my chest. â€œItâ€™s nice to finally meet you.â€
> 
> â€œYou know who I am?â€ he asks.
> 
> â€œYes.â€
> 
> But I donâ€™t know what heâ€™s doing here. Or what he plans to do to me. And I still donâ€™t know who Walt is, the other man in the room.
> 
> I keep my focus on the man in front of me. â€œYouâ€™re William Sinclair.â€
> 
> He stands up straighter. â€œI suppose it makes sense you would know that, given your interest in my family. Perhaps you thought youâ€™d come after me as well someday.â€
> 
> â€œCome after you? What are youâ€”â€
> 
> â€œItâ€™s not going to happen, Ms. Taylor.â€ He emphasizes the last name, my maiden name. â€œThis little scam youâ€™ve got going ends now. Whatever you used to blackmail my father, and are currently using to control my mother, it ends now. I will NOT let you continue this!â€
> 
> I jump up from the chair. â€œNo, thatâ€™s notâ€”â€
> 
> â€œSIT down!â€ He says it so loud and so forcefully that I freeze in place, afraid to move.
> 
> He waits for me to sit. I take a breath and slowly lower myself back into the chair. Iâ€™m about to tell him who I am but then he starts talking again. 
> 
> â€œI must say, you definitely played the part well. The poor girl from Iowa, just trying to get a better life for herself. And you couldâ€™ve done it, Jade. I know all about your past. You were valedictorian of your high school. You had all Aâ€™s at Moorhurst. Youâ€™re obviously a smart girl. You couldâ€™ve succeeded in life and done quite well for yourself. But you didnâ€™t want to wait for that success, did you? You didnâ€™t want to put the effort in. You went to Moorhurst and saw all that wealth around you, and you wanted a piece of it. So you latched onto Garret.â€ He shakes his head. â€œI wouldâ€™ve thought Pearce Kensington would know better. But you somehow managed to fool both him and his son.â€
> 
> â€œI didnâ€™t fool anyone. You donâ€™t understand. If youâ€™d just let me explain.â€
> 
> â€œYouâ€™re right. You didnâ€™t fool them. You blackmailed them, just like you blackmailed my father.â€
> 
> This is not how I saw this playing out. I imagined meeting William some day, but not like this. Not with him yelling at me, accusing me of things I didnâ€™t do.
> 
> â€œI didnâ€™t blackmail anyone. I donâ€™t know why you think that, but Iâ€™m telling you, I didnâ€™tâ€”â€
> 
> â€œI found the documents, Jade. After my father died, I took over his finances and discovered that last spring, a very large sum of money was put into an account in your name. Fifty million dollars, to be exact. Then I did some more investigating and found youâ€™d had five million of it transferred to a man in Iowa. The man who took you in after your mother died. Iâ€™m having him followed right now. And as soon as we have proof that heâ€™s in on this scam with you, heâ€™ll be arrested or dealt with some other way.â€
> 
> Now Iâ€™m pissed. William can say and think whatever he wants about me, but he canâ€™t involve Frank.
> 
> I bolt up from my chair. â€œYou are NOT arresting Frank! He didnâ€™t do anything! Youâ€™ve got this all wrong!â€ I look back at Walt who is still blocking the door. â€œCan you leave, please? I need to talk to William alone.â€
> 
> Walt doesnâ€™t move, so I turn back to William. â€œI need to talk to you alone. I need to tell you something. Something hardly anyone knows.â€
> 
> â€œIf you have something to say, just say it. But Iâ€™m telling you now Iâ€™m not going to believe your lies, Jade.â€
> 
> â€œItâ€™s not a lie. Itâ€™s a secret. And itâ€™s the truth. I swear. But Walt shouldnâ€™t know this. Itâ€™s better if he didnâ€™t.â€
> 
> â€œWaltâ€™s part of my private security team. Heâ€™s worked for me for the past 12 years. There are no secrets between us.â€
> 
> I glance at Walt again. I donâ€™t know what his story is. Maybe heâ€™s part of the organization or maybe heâ€™s just a security guy. Either way, he canâ€™t know my secret. He canâ€™t know Iâ€™m a Sinclair. At this point, Iâ€™m not even sure I want to tell William, but if I donâ€™t, heâ€™ll do something to me and I donâ€™t want to find out what that something is.
> 
> â€œI canâ€™t say this with Walt in the room,â€ I tell William. â€œIf you want to tell him later, thatâ€™s up to you. But right now, this needs to be just between you and me.â€
> 
> William looks back at Walt. â€œWait outside in the hall. But remain by the door.â€
> 
> Walt does as instructed, closing the door behind him.
> 
> Remain by the door? Whatâ€™s William think Iâ€™m going to do? Pull a knife on him? Iâ€™m half his size and I donâ€™t have a weapon. Iâ€™m the one whoâ€™s afraid of him. I donâ€™t know how heâ€™s going to react to this. What if he doesnâ€™t believe me? What if he still thinks Iâ€™m a criminal? What will he do to me?
> 
> My heartâ€™s racing again and I feel sick to my stomach. I wish Garret were here. He knows William. He could explain all this better than me, and William might actually believe him. And Garret could stop William from doing whatever heâ€™s planning to do to me.
> 
> William glares at me. â€œGo ahead.â€ 
> 
> I take a deep breath, then look directly at William and say, â€œIâ€™m your niece. Royce Sinclair was my father. I didnâ€™t know untilâ€”â€
> 
> â€œStop right there!â€ He puts his hand up. â€œI am not listening to this. You may have managed to con some very smart, very important people, but you are NOT going to do it to me.â€
> 
> â€œI swear to you, Iâ€™m not lying. Royce was working on a political campaign 20 years ago and he came to Des Moines during the caucus. He was there for a speech and he asked my mom out for dinner.â€
> 
> William huffs as he crosses his arms over his chest. â€œRoyce was married 20 years ago. He wouldnâ€™t ask a woman to dinner. You should really work on your story, Jade. At least try to make it believable.â€
> 
> â€œWould you just listen to me? I promise you, Iâ€™m not lying.â€
> 
> â€œSpoken like a true con artist. Youâ€™ve been doing this so long you believe your own lies.â€
> 
> â€œIâ€™m not a con artist. Iâ€™m trying to tell you the truth. Royce wasnâ€™t the man you thought he was. He did something really bad to my mom andâ€”â€
> 
> â€œHow dare you speak of my brother that way!â€ His arms drop to his sides and he takes a step closer, towering over me. â€œRoyce was a husband. A father. He wasnâ€™t perfect, but he was a decent man. And Iâ€™m not going to stand here and listen to you make up lies about him and your mother in order toâ€”â€
> 
> â€œHe raped her!â€ The anger I was trying to suppress suddenly explodes.
> 
> I didnâ€™t want to tell William this and I didnâ€™t think I ever would. I never thought Iâ€™d meet him. But here we are, face-to-face, and I canâ€™t take another second of this. I canâ€™t stand here and listen to him accuse me like this, making it sound Iike Iâ€™m the bad one. Like I did something wrong. And I hate the way heâ€™s sticking up for his brother, the man who committed a horrible crime against my mom. The man who destroyed her life, and mine. The man who killed my momâ€™s parents. The man who tried to kill me and almost killed Garret. 
> 
> William backs away, but I donâ€™t see his expression. I keep my eyes on the floor.

Here is Kevin's (without using ASCII conversion):


Here is yours (ASCII conversation not an option):

> title: Becoming Us: The Jade Series #7
> author: Allie Everhart
> description: <p>Jade and Garret thought the robbery in their neighborhood had nothing to do with them, but the pieces are finally starting to come together. Someone's been working behind the scenes, pulling the strings to determine Garret's fate.  </p><p>The timing couldn't be worse. Jade and Garret are talking things out, becoming even closer, making plans for their future. Plans that might never happen.  </p><p>When Garret finally learns the truth, he's left with an agonizing discovery about the past and an ultimatum regarding the future. </p><p>**</p>
> 
> 
> 
> -----
> 
> Contents
> 
> 
> [Title Page][1]
> 
> [Copyright][2]
> 
> [1][3]
> 
> [2][4]
> 
> [3][5]
> 
> [4][6]
> 
> [5][7]
> 
> [6][8]
> 
> [7][9]
> 
> [8][10]
> 
> [9][11]
> 
> [10][12]
> 
> [11][13]
> 
> [12][14]
> 
> [13][15]
> 
> [14][16]
> 
> [15][17]
> 
> [16][18]
> 
> [17][19]
> 
> [18][20]
> 
> [19][21]
> 
> [20][22]
> 
> [21][23]
> 
> [22][24]
> 
> [23][25]
> 
> [24][26]
> 
> [25][27]
> 
> [26][28]
> 
> [1] ../Text/part0001.html
> [2] ../Text/part0002.html
> [3] ../Text/part0003.html
> [4] ../Text/part0004.html
> [5] ../Text/part0005.html
> [6] ../Text/part0006.html
> [7] ../Text/part0007.html
> [8] ../Text/part0008.html
> [9] ../Text/part0009.html
> [10] ../Text/part0010.html
> [11] ../Text/part0011.html
> [12] ../Text/part0012.html
> [13] ../Text/part0013.html
> [14] ../Text/part0014.html
> [15] ../Text/part0015.html
> [16] ../Text/part0016.html
> [17] ../Text/part0017.html
> [18] ../Text/part0018.html
> [19] ../Text/part0019.html
> [20] ../Text/part0020.html
> [21] ../Text/part0021.html
> [22] ../Text/part0022.html
> [23] ../Text/part0023.html
> [24] ../Text/part0024.html
> [25] ../Text/part0025.html
> [26] ../Text/part0026.html
> [27] ../Text/part0027.html
> [28] ../Text/part0028.html
> 
> -----
> 
> Becoming Us
> 
> 
> By Allie Everhart
> 
> -----
> 
> Becoming Us
> 
> By Allie Everhart
> 
> 
> 
> Copyright © 2014 Allie Everhart
> 
> All rights reserved.
> 
> Published by Waltham Publishing, LLC
> 
> Cover Design by Sarah Hansen of Okay Creations
> 
> Photo by Toski Covey Photography
> 
> 
> 
> 
> This book is a work of fiction. The characters, things, and events are fictitious, and any similarities to real persons (live or dead), things, or events are coincidental and not intended by the author. Brand names of products mentioned in this book are
> used for reference only and the author acknowledges that any trademarks and product names are the property of their respective owners.
> 
> 
> The author holds exclusive rights to this work and unauthorized duplication is prohibited. No part of this book is to be reproduced in any form without written permission from the author.
> 
> 
> 
> 
> -----
> 
> 1
> 
> JADE
> 
> The man stands in front of me as I sit in the chair. We’re in a small room in an abandoned building on the Camsburg campus. The man is tall, maybe 6’2, with dark hair that has flecks of gray in it. He looks handsome and sophisticated, wearing a black
> tailored suit. He has an average build, maybe a little on the thin side. His eyes are greenish-brown, his skin has a slight tan, and his face is just like his father’s. I hadn’t realized how similar they look. I’ve only seen a couple photos, but seeing
> him up close, he looks just like his dad, even more so than his brother did.
> 
> I meet his gaze, trying to remain calm even though my heart is pounding in my chest. “It’s nice to finally meet you.”
> 
> “You know who I am?” he asks.
> 
> “Yes.”
> 
> But I don’t know what he’s doing here. Or what he plans to do to me. And I still don’t know who Walt is, the other man in the room.
> 
> I keep my focus on the man in front of me. “You’re William Sinclair.”
> 
> He stands up straighter. “I suppose it makes sense you would know that, given your interest in my family. Perhaps you thought you’d come after me as well someday.”
> 
> “Come after you? What are you—”
> 
> “It’s not going to happen, Ms. Taylor.” He emphasizes the last name, my maiden name. “This little scam you’ve got going ends now. Whatever you used to blackmail my father, and are currently using to control my mother, it ends now. I will NOT let you
> continue this!”
> 
> I jump up from the chair. “No, that’s not—”
> 
> “SIT down!” He says it so loud and so forcefully that I freeze in place, afraid to move.
> 
> He waits for me to sit. I take a breath and slowly lower myself back into the chair. I’m about to tell him who I am but then he starts talking again.
> 
> “I must say, you definitely played the part well. The poor girl from Iowa, just trying to get a better life for herself. And you could’ve done it, Jade. I know all about your past. You were valedictorian of your high school. You had all A’s at Moorhurst.
> You’re obviously a smart girl. You could’ve succeeded in life and done quite well for yourself. But you didn’t want to wait for that success, did you? You didn’t want to put the effort in. You went to Moorhurst and saw all that wealth around you, and you
> wanted a piece of it. So you latched onto Garret.” He shakes his head. “I would’ve thought Pearce Kensington would know better. But you somehow managed to fool both him and his son.”
> 
> “I didn’t fool anyone. You don’t understand. If you’d just let me explain.”
> 
> “You’re right. You didn’t fool them. You blackmailed them, just like you blackmailed my father.”
> 
> This is not how I saw this playing out. I imagined meeting William some day, but not like this. Not with him yelling at me, accusing me of things I didn’t do.
> 
> “I didn’t blackmail anyone. I don’t know why you think that, but I’m telling you, I didn’t—”
> 
> “I found the documents, Jade. After my father died, I took over his finances and discovered that last spring, a very large sum of money was put into an account in your name. Fifty million dollars, to be exact. Then I did some more investigating and found
> you’d had five million of it transferred to a man in Iowa. The man who took you in after your mother died. I’m having him followed right now. And as soon as we have proof that he’s in on this scam with you, he’ll be arrested or dealt with some other way.”
> 
> Now I’m pissed. William can say and think whatever he wants about me, but he can’t involve Frank.
> 
> I bolt up from my chair. “You are NOT arresting Frank! He didn’t do anything! You’ve got this all wrong!” I look back at Walt who is still blocking the door. “Can you leave, please? I need to talk to William alone.”
> 
> Walt doesn’t move, so I turn back to William. “I need to talk to you alone. I need to tell you something. Something hardly anyone knows.”
> 
> “If you have something to say, just say it. But I’m telling you now I’m not going to believe your lies, Jade.”
> 
> “It’s not a lie. It’s a secret. And it’s the truth. I swear. But Walt shouldn’t know this. It’s better if he didn’t.”
> 
> “Walt’s part of my private security team. He’s worked for me for the past 12 years. There are no secrets between us.”
> 
> I glance at Walt again. I don’t know what his story is. Maybe he’s part of the organization or maybe he’s just a security guy. Either way, he can’t know my secret. He can’t know I’m a Sinclair. At this point, I’m not even sure I want to tell William, but
> if I don’t, he’ll do something to me and I don’t want to find out what that something is.
> 
> “I can’t say this with Walt in the room,” I tell William. “If you want to tell him later, that’s up to you. But right now, this needs to be just between you and me.”
> 
> William looks back at Walt. “Wait outside in the hall. But remain by the door.”
> 
> Walt does as instructed, closing the door behind him.
> 
> Remain by the door? What’s William think I’m going to do? Pull a knife on him? I’m half his size and I don’t have a weapon. I’m the one who’s afraid of him. I don’t know how he’s going to react to this. What if he doesn’t believe me? What if he still
> thinks I’m a criminal? What will he do to me?
> 
> My heart’s racing again and I feel sick to my stomach. I wish Garret were here. He knows William. He could explain all this better than me, and William might actually believe him. And Garret could stop William from doing whatever he’s planning to do to
> me.
> 
> William glares at me. “Go ahead.”
> 
> I take a deep breath, then look directly at William and say, “I’m your niece. Royce Sinclair was my father. I didn’t know until—”
> 
> “Stop right there!” He puts his hand up. “I am not listening to this. You may have managed to con some very smart, very important people, but you are NOT going to do it to me.”
> 
> “I swear to you, I’m not lying. Royce was working on a political campaign 20 years ago and he came to Des Moines during the caucus. He was there for a speech and he asked my mom out for dinner.”
> 
> William huffs as he crosses his arms over his chest. “Royce was married 20 years ago. He wouldn’t ask a woman to dinner. You should really work on your story, Jade. At least try to make it believable.”
> 
> “Would you just listen to me? I promise you, I’m not lying.”
> 
> “Spoken like a true con artist. You’ve been doing this so long you believe your own lies.”
> 
> “I’m not a con artist. I’m trying to tell you the truth. Royce wasn’t the man you thought he was. He did something really bad to my mom and—”
> 
> “How dare you speak of my brother that way!” His arms drop to his sides and he takes a step closer, towering over me. “Royce was a husband. A father. He wasn’t perfect, but he was a decent man. And I’m not going to stand here and listen to you make up
> lies about him and your mother in order to—”
> 
> “He raped her!” The anger I was trying to suppress suddenly explodes.
> 
> I didn’t want to tell William this and I didn’t think I ever would. I never thought I’d meet him. But here we are, face-to-face, and I can’t take another second of this. I can’t stand here and listen to him accuse me like this, making it sound Iike I’m
> the bad one. Like I did something wrong. And I hate the way he’s sticking up for his brother, the man who committed a horrible crime against my mom. The man who destroyed her life, and mine. The man who killed my mom’s parents. The man who tried to kill
> me and almost killed Garret.
> 
> William backs away, but I don’t see his expression. I keep my eyes on the floor.
> 


I would suggest that you change your name from epub2txt to epub-txt or epub-textify or even repub2txt, as KevinBoone's program was first and you do the exact same thing you probably shouldn't have the same name.

**Comment by quininer** [comment]
Thank for your work. the result looks good.

I never knew kevinboone/epub2txt before, I think this is a more common name, don't need to avoid it.

**Comment by teamcoltra** [comment]
I'm closing this as I addressed what needs to be addressed. I still think the name should probably be changed but that's up to you. :) Good work @quininer
